
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-mysql
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql-test
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql-test
    spec:
      containers:
        - name: springboot-k8s-mysql-test
          image: akashkale/spring-boot-healthcare
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables                  
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            - name: DB_NAME  # Setting Database name from configMap
              value: k8s
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root@123
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-k8s-svc 
spec:
  selector:
    app: springboot-k8s-mysql-test
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      
  type: NodePort # type of the service.
